image: python:3.8-alpine

pages:
  stage: deploy
  tags:
    - docker
  only:
    - main
  script:
    - pip install mkdocs-material
    - cd documentation
    - mkdocs build --site-dir ${CI_PROJECT_DIR}/public
  artifacts:
    paths:
      - public
