site_name: Cast Iron
theme:
  name: material
  palette:
    scheme: preference
  favicon: images/bclogo_notext.png
repo_name: black-cape/cast-iron
nav:
  - 'Getting Started': index.md
  - Setup:
    - 'Object Stores':
      - object-stores/aws-s3.md
      - object-stores/minio.md
    - 'Message Queues':
      - message-queues/kafka.md
      - message-queues/nats.md
    - Workers:
      - workers/celery.md
      - workers/faust.md
    - ETL:
      - etl/bash.md
      - etl/python.md
    - Databases:
      - databases/mssql.md
      - databases/mysql.md
      - databases/postgres.md
      - databases/sqlite.md
extra_css:
  - stylesheets/extra.css
